# Generated by Django 3.2.5 on 2023-06-10 02:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import elink.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polaris', '0014_auto_20220211_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElinkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('username', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElinkPaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ElinkStellarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True, null=True)),
                ('memo_type', models.TextField(blank=True, null=True)),
                ('account', models.CharField(max_length=56, validators=[django.core.validators.MinLengthValidator(2)])),
                ('muxed_account', models.TextField(blank=True, null=True)),
                ('secret_key', models.CharField(max_length=56, validators=[django.core.validators.MinLengthValidator(2)])),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmation_token', models.CharField(default=elink.models.get_new_token, max_length=36)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('memo', 'account', 'muxed_account', 'secret_key')},
            },
        ),
        migrations.CreateModel(
            name='OffChainAssetExtra',
            fields=[
                ('offchain_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polaris.offchainasset')),
                ('fee_fixed', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('fee_percent', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ElinkUserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.TextField(db_index=True)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elink.elinkstellaraccount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElinkUserMonoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mono_trasaction_type', models.CharField(max_length=30)),
                ('mono_account', models.CharField(max_length=50)),
                ('mono_amount', models.IntegerField()),
                ('mono_created_at', models.CharField(max_length=50)),
                ('mono_currency', models.CharField(max_length=10)),
                ('mono_customer', models.CharField(blank=True, max_length=50, null=True)),
                ('mono_description', models.CharField(max_length=100)),
                ('mono_fee', models.IntegerField()),
                ('mono_id', models.CharField(max_length=50)),
                ('mono_live_mode', models.BooleanField()),
                ('mono_reference', models.CharField(max_length=50)),
                ('mono_status', models.CharField(max_length=20)),
                ('mono_updated_at', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElinkUserKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=254)),
                ('address_2', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=15)),
                ('bvn', models.CharField(max_length=11)),
                ('payment_account', models.CharField(max_length=10)),
                ('payment_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elink.elinkpaymentprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElinkPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('INITIALIZED', 'INITIALIZED'), ('FAILED', 'FAILED')], default='INITIALIZED', max_length=20)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polaris.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ElinkFundingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('payment_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elink.elinkpaymentprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElinkCustodyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('payment_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elink.elinkpaymentprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
