# Generated by Django 3.2.5 on 2022-10-25 15:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import elink.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polaris', '0014_auto_20220211_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElinkPaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ElinkStellarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True, null=True)),
                ('memo_type', models.TextField(blank=True, null=True)),
                ('account', models.CharField(max_length=56, validators=[django.core.validators.MinLengthValidator(2)])),
                ('muxed_account', models.TextField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmation_token', models.CharField(default=elink.models.get_new_token, max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='ElinkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('wallet_id', models.CharField(max_length=50, unique=True)),
                ('bank_account_number', models.CharField(max_length=254, null=True)),
                ('bank_number', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OffChainAssetExtra',
            fields=[
                ('offchain_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polaris.offchainasset')),
                ('fee_fixed', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('fee_percent', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ElinkUserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.TextField(db_index=True)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elink.elinkstellaraccount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elink.elinkuser')),
            ],
        ),
        migrations.CreateModel(
            name='ElinkUserKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=254)),
                ('address_2', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=15)),
                ('bvn', models.CharField(max_length=11)),
                ('payment_account', models.CharField(max_length=10)),
                ('payment_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elink.elinkpaymentprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elink.elinkuser')),
            ],
        ),
        migrations.AddField(
            model_name='elinkstellaraccount',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='elink.elinkuser'),
        ),
        migrations.CreateModel(
            name='ElinkPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('INITIALIZED', 'INITIALIZED'), ('FAILED', 'FAILED')], default='INITIALIZED', max_length=20)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polaris.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ElinkFundingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('payment_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elink.elinkpaymentprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elink.elinkuser')),
            ],
        ),
        migrations.CreateModel(
            name='ElinkCustodyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('payment_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elink.elinkpaymentprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elink.elinkuser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='elinkstellaraccount',
            unique_together={('memo', 'account', 'muxed_account')},
        ),
    ]
