# Generated by Django 3.2.5 on 2022-07-11 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elink', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PolarisStellarAccount',
            new_name='ElinkStellarAccount',
        ),
        migrations.RenameModel(
            old_name='PolarisUser',
            new_name='ElinkUser',
        ),
        migrations.RenameModel(
            old_name='PolarisUserTransaction',
            new_name='ElinkUserTransaction',
        ),
    ]
