# Generated by Django 3.2.5 on 2023-06-10 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elink', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elinkuser',
            name='username',
        ),
    ]
