# Generated by Django 3.2.5 on 2022-10-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elinkuser',
            name='wallet_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
