# Generated by Django 3.2.5 on 2022-07-14 12:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elink', '0002_auto_20220711_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elinkstellaraccount',
            name='account',
            field=models.CharField(max_length=56, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='elinkstellaraccount',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='elink.elinkuser'),
        ),
    ]
