# Generated by Django 3.2.5 on 2023-06-10 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elink', '0002_remove_elinkuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='elinkuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='elinkstellaraccount',
            name='account',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='elinkstellaraccount',
            name='secret_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='elinkstellaraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='elinkstellaraccount',
            unique_together={('memo', 'account', 'muxed_account')},
        ),
    ]
