# Generated by Django 3.2.5 on 2023-06-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('elink', '0003_auto_20230610_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='elinkuser',
            name='user_permissions',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
    ]
