# Generated by Django 3.2.5 on 2022-07-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elink', '0003_auto_20220714_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='elinkuser',
            name='full_address',
            field=models.CharField(default='zzz', max_length=254),
            preserve_default=False,
        ),
    ]
