# Generated by Django 3.2.5 on 2022-07-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elink', '0004_elinkuser_full_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elinkuser',
            name='full_address',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
