# Generated by Django 3.2.5 on 2022-07-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elink', '0005_alter_elinkuser_full_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elinkuser',
            name='full_address',
        ),
        migrations.CreateModel(
            name='ElinkUserKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=254)),
                ('address_2', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elink.elinkuser')),
            ],
        ),
    ]
