# Generated by Django 3.2.5 on 2022-07-28 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0014_auto_20220211_0624'),
        ('elink', '0006_auto_20220721_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElinkPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('INITIALIZED', 'INITIALIZED'), ('FAILED', 'FAILED')], default='INITIALIZED', max_length=20)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polaris.transaction')),
            ],
        ),
    ]
